### ISSUE TITLE
Does not work with Python 3

### ISSUE THREAD

**Issue by AESM** [smazhara/awesome_print#2]
I was curious if there was going to be an update to make this compatible with Python 3.

>NOTE: I made sure `pip2` and `pip3` had the package properly installed

### File Being Run
``` py
# test_file.py
from awesome_print import ap

ap('Hello!')
```

### Python 2
``` sh
## Results of running `python2 test_file.py`

Hello!
```

### Python 3
``` sh
## Results of running `python3 test_file.py`

Traceback (most recent call last):
  File "test_file.py", line 4, in <module>
    from awesome_print import ap
  File "/usr/local/lib/python3.5/site-packages/awesome_print/__init__.py", line 1, in <module>
    from awesome_print import ap
ImportError: cannot import name 'ap'
```

**Comment by addrians** [comment]
The initial error is just the way modules are imported in python2 vs. python3 and it's fixed by adding a dot:
`from .awesome_print import ap`

However, the `__builtin__` module is replaced by the `builtins` module in python3 and further the `types` module is totally different. So a total rewrite is required or sticking with the builtin [pprint](https://docs.python.org/3/library/pprint.html) library.

**Comment by satreix** [comment]
I have a working py3 version of this. Is anyone interested in me digging into [six](https://pypi.python.org/pypi/six) to have a py2/py3 PR for this?

**Comment by AESM** [comment]
@satreix - I would totally be into that!

**Comment by satreix** [comment]
@smazhara are you still working on this? How can I help make it happen?

**Comment by 0xD7ba952CE8A0976e8d9852b7649bf01c30146** [comment]
@satreix can you share where you have your working Python 3 version? I don't see it forked on your profile.

**Comment by satreix** [comment]
@gnycl I created #4.
